// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfcax9rpzoJCXkKLUM5QipLmtORB05Eew',
    appId: '1:909679089735:web:3d64fffc10ea08f869f962',
    messagingSenderId: '909679089735',
    projectId: 'brew-crew-ba02c',
    authDomain: 'brew-crew-ba02c.firebaseapp.com',
    storageBucket: 'brew-crew-ba02c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNZM6XKuhCzjzNA8SAUCA5O5_vvIGbiFE',
    appId: '1:909679089735:android:87784607d5d15f8169f962',
    messagingSenderId: '909679089735',
    projectId: 'brew-crew-ba02c',
    storageBucket: 'brew-crew-ba02c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4q_bB2vRLwEa6uF1fPi4mEhjUm_-isBY',
    appId: '1:909679089735:ios:3acb277d2b7d398069f962',
    messagingSenderId: '909679089735',
    projectId: 'brew-crew-ba02c',
    storageBucket: 'brew-crew-ba02c.appspot.com',
    iosBundleId: 'com.example.brewCrew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4q_bB2vRLwEa6uF1fPi4mEhjUm_-isBY',
    appId: '1:909679089735:ios:3acb277d2b7d398069f962',
    messagingSenderId: '909679089735',
    projectId: 'brew-crew-ba02c',
    storageBucket: 'brew-crew-ba02c.appspot.com',
    iosBundleId: 'com.example.brewCrew',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAfcax9rpzoJCXkKLUM5QipLmtORB05Eew',
    appId: '1:909679089735:web:3f4724d222cc7d6e69f962',
    messagingSenderId: '909679089735',
    projectId: 'brew-crew-ba02c',
    authDomain: 'brew-crew-ba02c.firebaseapp.com',
    storageBucket: 'brew-crew-ba02c.appspot.com',
  );
}
